name: storage
version: '${project.version}'
main: me.ava_l4nch.storage.Storage
api-version: '1.20'
commands:
  hello:
    description: testing stuff
  store:
    description: to store blocks in the world
  load:
    description: loads the storage
